field: 3fc177c0-dac8-484c-818b-e0af6634e160 # Tags
fieldLayouts:
  462ff6c7-ac34-45ff-b121-1e3446ab8e07:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b5b64794-79b0-4f45-bafa-da0addf4f5c4 # Tag
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7315ed7d-5649-49ba-a013-dbe2e442ff67
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: be72e181-220b-41b3-bd17-764bdd4c4a79 # Position
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e3aa2b57-feec-4b56-999d-38d561b8777c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7d21047d-b4d5-42fc-ba12-45781a43642d
        userCondition: null
fields:
  b5b64794-79b0-4f45-bafa-da0addf4f5c4: # Tag
    columnSuffix: jlcmwnrf
    contentColumnType: text
    fieldGroup: null
    handle: tag
    instructions: null
    name: Tag
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  be72e181-220b-41b3-bd17-764bdd4c4a79: # Position
    columnSuffix: whmfknko
    contentColumnType: string(7)
    fieldGroup: null
    handle: position
    instructions: null
    name: Position
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Head
            -
              - value
              - head
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Body End'
            -
              - value
              - bodyEnd
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: tag
name: Tag
sortOrder: 1
