columnSuffix: null
contentColumnType: string
fieldGroup: c18afe66-b83b-45ea-ab40-89602795ee45 # Meta
handle: tags
instructions: null
name: Tags
searchable: false
settings:
  contentTable: '{{%matrixcontent_tags}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
